language: ruby
cache: bundler

rvm:
- 2.7
- 3.0
- 3.1

before_install:
  - sudo apt-get update
  - sudo apt-get install python
  - nvm install node
  - nvm use node
  - gem install bundler

install:
  - pip install --user bumpversion
  - npm install -g semantic-release
  - npm install -g @semantic-release/exec
  - npm install -g @semantic-release/git
  - npm install @semantic-release/github
  - npm install -g @semantic-release/commit-analyzer
  - bundle install

script:
  - bundle exec rake

deploy:
  - provider: script
    script: npx semantic-release
    on:
      branch: main
      rvm: 2.7

  - provider: rubygems
    api_key: $RUBYGEMS_API_KEY
    gem: ibm_cloud_sdk_core
    on:
      branch: main
      rvm: 2.7

matrix:
  fast_finish: true

notifications:
  email: false
